# Generated by Django 5.1.1 on 2024-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_contact_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(),
        ),
    ]
